### ISSUE TITLE
#220 Err while building ORB SLAM PACKAGE

### ISSUE THREAD

**Issue by tahmine-iaun** [raulmur/ORB_SLAM#120]
![issue](https://cloud.githubusercontent.com/assets/17230648/18305988/17fe8288-74ff-11e6-95c2-38aa07a4bf1b.jpg)

Hi....
I faced with this issue could you pls help me to solve that?

**Comment by chaiein** [comment]
Its a memory related issue. Abort core dump is one of the common issue i faced, may be if u allocate sufficient memory it will not cause this issue. I reinstalled vm and ubuntu as i didnt find solution.

**Comment by tahmine-iaun** [comment]
@chaiein  Yes, you were right.
i reinstalled it again , :+1:
