### ISSUE TITLE
fail to get image

### ISSUE THREAD

**Issue by tahmine-iaun** [raulmur/ORB_SLAM#125]
![screenshot from 2016-12-25 00 03 45](https://cloud.githubusercontent.com/assets/17230648/21468706/c8f801b8-ca36-11e6-82a7-b4c2058bc4f2.png)
does anyone can help me with that?

**Comment by chaiein** [comment]
check your camera connected or not?

**Comment by tahmine-iaun** [comment]
@chaiein  tnx for your reply I've solved that actually it was launch file error :)
