### ISSUE TITLE
How to create ORB vocabulary from dataset?

### ISSUE THREAD

**Issue by bjornph** [raulmur/ORB_SLAM#13]
While I have managed to get your example file to work, I struggle with providing an ORB vocabulary from my own dataset. I have a set of image files converted to a .bag file. 

How do you extract ORB features from an image dataset to provide to ORB-SLAM?

**Comment by raulmur** [comment]
You do not need to create another visual vocabulary. The vocabulary we provide was taken with a very big dataset with indoor and outdoor images. We have always used the same vocabulary in our experiments achieving very good performance. If you are still interested in creating your own, you have to use the DBoW2 library (https://github.com/dorian3d/DBoW2).

**Comment by amc-nu** [comment]
Raul, could you tell us which image dataset did you use to create the dictionary?

Gracias!

**Comment by jingpang** [comment]
@amc-nu , the dataset is here (http://www.rawseeds.org/rs/datasets/view//7) , 'Bovisa_2008-09-01',
according to this paper by the author 'Fast Relocalisation and Loop Closing in Keyframe-Based SLAM
'. But i failed to download it...

**Comment by KathiravanNatarajan** [comment]
what does ORB vocabulary mean ? I am new to this . if someone explains me, it'd be great

**Comment by KathiravanNatarajan** [comment]
can we implement this ORB_SLAM for ARDRONE ? should I have to make any changes for that ?

**Comment by chaiein** [comment]
you can get answer here https://www.zhihu.com/question/49153462.

**Comment by KathiravanNatarajan** [comment]
@chaiein  : Hi,
I have got rviz(something is running) and rqt_image window with the output of ardrone/front/image_raw.

How can I get the 3D model of the environment using the existing code ? I have downloaded bag file too. Does bag file have anything to do with 3D model ? Does the code already contain a way to generate the 3D model ? 
It'll be a great help if you can answer this. I couldn't get help from anyone.

**Comment by manthan99** [comment]
Please checkout this repo where I have added step by step instructions to create own vocabulary for ORB SLAM
https://github.com/manthan99/ORB_SLAM_vocab-build

**Comment by KlemenDEV** [comment]
Do we need to prepare our dataset from un-distorted camera images, or does this not matter? And should the image size be the same as the images we will be working on, or does scale not matter?

**Comment by TonyPhh** [comment]
> @amc-nu , the dataset is here (http://www.rawseeds.org/rs/datasets/view//7) , 'Bovisa_2008-09-01', according to this paper by the author 'Fast Relocalisation and Loop Closing in Keyframe-Based SLAM '. But i failed to download it...

hello，can you download the ‘Bovisa_2008-09-01’ dataset? I get some trouble and have difficulty downloading the 'Bovisa_2008-09-01' dataset. thanks!
