### ISSUE TITLE
ORB_SLAM IMU combination issue 

### ISSUE THREAD

**Issue by amranov** [raulmur/ORB_SLAM#143]
Hi , 
at first i would like to thank you for this wondrfull open source work 
so ,
i'm working on VISUAL-inertial SLAM project using ORB_SLAM  algorithm  , i include some c++ code on trcking.cc oprimizer.cc to combinate IMU and ORB
i rebuild ORB succesfully , 
amrani@amrani:~/ORB_SLAM/build$ cmake .. -DROS_BUILD_TYPE=Release
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
[rosbuild] Building package ORB_SLAM
[rosbuild] Cached build flags older than manifests; calling rospack to get flags
-- Using CATKIN_DEVEL_PREFIX: /home/amrani/ORB_SLAM/build/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/indigo
-- This workspace overlays: /opt/ros/indigo
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Skip enable_testing() for dry packages
-- Using CATKIN_TEST_RESULTS_DIR: /home/amrani/ORB_SLAM/build/test_results
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.6.18
[rosbuild] using multiarch 'x86_64-linux-gnu' for finding Boost
-- Using these message generators: gencpp;genlisp;genpy
[rosbuild] Including /opt/ros/indigo/share/roslisp/rosbuild/roslisp.cmake
[rosbuild] Including /opt/ros/indigo/share/roscpp/rosbuild/roscpp.cmake
[rosbuild] Including /opt/ros/indigo/share/rospy/rosbuild/rospy.cmake
Build type: Release
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/amrani/ORB_SLAM/build
amrani@amrani:~/ORB_SLAM/build$ make
Scanning dependencies of target rospack_genmsg_libexe
[  0%] Built target rospack_genmsg_libexe
Scanning dependencies of target rosbuild_precompile
[  0%] Built target rosbuild_precompile
Scanning dependencies of target ORB_SLAM
[  5%] Building CXX object CMakeFiles/ORB_SLAM.dir/src/main.cc.o
[ 11%] Building CXX object CMakeFiles/ORB_SLAM.dir/src/Tracking.cc.o
[ 16%] Building CXX object CMakeFiles/ORB_SLAM.dir/src/LocalMapping.cc.o
[ 22%] Building CXX object CMakeFiles/ORB_SLAM.dir/src/LoopClosing.cc.o
[ 27%] Building CXX object CMakeFiles/ORB_SLAM.dir/src/ORBextractor.cc.o
[ 33%] Building CXX object CMakeFiles/ORB_SLAM.dir/src/ORBmatcher.cc.o
[ 38%] Building CXX object CMakeFiles/ORB_SLAM.dir/src/FramePublisher.cc.o
[ 44%] Building CXX object CMakeFiles/ORB_SLAM.dir/src/Converter.cc.o
[ 50%] Building CXX object CMakeFiles/ORB_SLAM.dir/src/MapPoint.cc.o
[ 55%] Building CXX object CMakeFiles/ORB_SLAM.dir/src/KeyFrame.cc.o
[ 61%] Building CXX object CMakeFiles/ORB_SLAM.dir/src/Map.cc.o
[ 66%] Building CXX object CMakeFiles/ORB_SLAM.dir/src/MapPublisher.cc.o
[ 72%] Building CXX object CMakeFiles/ORB_SLAM.dir/src/Optimizer.cc.o
[ 77%] Building CXX object CMakeFiles/ORB_SLAM.dir/src/PnPsolver.cc.o
[ 83%] Building CXX object CMakeFiles/ORB_SLAM.dir/src/Frame.cc.o
[ 88%] Building CXX object CMakeFiles/ORB_SLAM.dir/src/KeyFrameDatabase.cc.o
[ 94%] Building CXX object CMakeFiles/ORB_SLAM.dir/src/Sim3Solver.cc.o
[100%] Building CXX object CMakeFiles/ORB_SLAM.dir/src/Initializer.cc.o
Linking CXX executable ../bin/ORB_SLAM
[100%] Built target ORB_SLAM

but whene i try to run roslaunch ExampleFuerte.launch I got this error 
![screenshot from 2017-06-22 15_34_21](https://user-images.githubusercontent.com/29498250/27463952-339ad302-57fd-11e7-8824-1ddf1b8f7d5d.png)
i am using VI-SENSOR 
ubuntu indigo 14.04 
CPU INTEL I5-6200U 2.8GHz
regards ,

**Comment by laxnpander** [comment]
The error message does not help. There is no valuable informations to give advice to, especially as you have modified the code yourself. Obviously your node crashes somewhere, but we can't know where. Try to find out more! You might launch with valgrind activated:
http://wiki.ros.org/roslaunch/Tutorials/Roslaunch%20Nodes%20in%20Valgrind%20or%20GDB

This wil detect some memory leaks, but can take some time.
