### ISSUE TITLE
How  to start  camera node with  my  image sequences in the 4th step?

### ISSUE THREAD

**Issue by HChengmeng** [raulmur/ORB_SLAM#35]
I am a freshman of ROS. I follow the usage step by step. But I  really don know how  to start  camera node with  my  image sequences in the 4th step.  I downloaded image sequences under a folder.

What should I do ? Thanks

**Comment by Oblynx** [comment]
Hi, if you had a live webcamera feed, I would suggest the usb_cam
<http://wiki.ros.org/usb_cam> or the libuvc_camera
<http://wiki.ros.org/libuvc_camera> ros package.

On 11 June 2015 at 06:23, HChengmeng <notifications@github.com> wrote:

> I am a freshman of ROS. I follow the usage step by step. But I really don
> know how to start camera node with my image sequences in the 4th step. I
> downloaded image sequences under a floder.
>
> What should I do ? Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/raulmur/ORB_SLAM/issues/35>.
>



-- 
*        Lynx*

**Comment by HChengmeng** [comment]
@Oblynx Thank you!

**Comment by raulmur** [comment]
@HChengmeng if you have a sequence of images (in a folder), you can generate a rosbag with https://github.com/raulmur/BagFromImages  and then play it as explained in 5.3
