### ISSUE TITLE
only seeing polygons in rviz

### ISSUE THREAD

**Issue by ssampang** [raulmur/ORB_SLAM#52]
Hi guys,

ORB-SLAM itself seems to be working fine (features tracking well), but I can't visualize the 3D map in rviz at all. I see very weird shapes/polygons instead. Here's a [screenshot](http://imgur.com/i1q4YBK). Any help would be appreciated.

Thanks,
Sid

**Comment by navidmostofi** [comment]
I have the same problem!, its strange for me before it was working fine

**Comment by ssampang** [comment]
Just had to restart the computer...-_-
