### ISSUE TITLE
Using ATAN camera model

### ISSUE THREAD

**Issue by ssampang** [raulmur/ORB_SLAM#53]
I'm using a very wide FOV camera (go pro), so I'd like to use the FOV camera model (Deverneay and Faugeras) instead of the provided model that OpenCV uses. I believe I've modified the code correctly, as I've double-checked my math by hand (by observing and verifying the final undistorted coordinates I feed back into the ORB-SLAM code) and the features have no problems tracking near the center of the frame. However, I'm having trouble with disappearing features at the edges of the frame (maybe the first 20% of each edge), so I wanted to check here and see if the authors had maybe implemented some checks to delete features that were corrected by the calibration to be too far outside of the image bounds eg. a feature at (10,10) in an image of size (1920,1080) that was then corrected to (-150,-50).

In case I haven't analyzed the ORB-SLAM code well, I should probably also mention what changes I've made to switch to the FOV model. In `Data/Settings.yaml`, I set `fx,fy,cx,cy` according to my calibration, and set `k1,k2,p1,p2` to 0. I modified the call to `cv::undistortPoints` made in `Frame.cc:UndistortKeyPoints` and removed the last parameter. This allowed `cv::undistortPoints` to return normalized coordinates, which I then fed into my own function to account for radial distortion. I set the contents of `mat` to the values my function returned.
 
Thanks,
Sid

**Comment by Oblynx** [comment]
Hello Sid,

Do you have your modifications in a fork here on Github by any chance? I'd
love to take a look.

Thanks,
Konstantinos

*-------------------------------------------------------*
*  Konstantinos Samaras-Tsakiris*
School of Electrical and Computer Engineering
Aristotle University of Thessaloniki

**Comment by HemangShah1** [comment]
Hi,

Each map point gets checked whether it is in frustum (angle is checked). See the function: Frame::isInFrustum.

hth,

**Comment by ssampang** [comment]
Hi guys,

@Oblynx Oblynx: Unfortunately, I can't share the code without approval from my employer, which is a long process.

@HemangShah1: Thanks for the tip! Looking at `Frame::isInFrustum` led me to look at `Frame::ComputeImageBounds`, which was also calling `cv::undistortPoints`. I simply had to call my function there as well, and the code works now. 

Thanks again,
Sid
