### ISSUE TITLE
Which image set was the default dictionary created with?

### ISSUE THREAD

**Issue by MarcGyongyosi** [raulmur/ORB_SLAM#54]
I have been trying to find any kind of reference to answer this question, but couldn't find anything neither in the paper nor here on github. Is the image set available somewhere?

-Marc

**Comment by MarcGyongyosi** [comment]
@raulmur could you provide any info on what image set you used to create the default vocabulary?

**Comment by raulmur** [comment]
Check our ICRA '14 Paper: 
http://webdiis.unizar.es/~jdtardos/papers/2014_IEEE_ICRA_Mur_Tardos.pdf
(section III.B)

Best,
Raúl

**Comment by MarcGyongyosi** [comment]
Thank you very much!

-Marc
