### ISSUE TITLE
Fundamental Matrix fails

### ISSUE THREAD

**Issue by sneuma12** [raulmur/ORB_SLAM#56]
Hello,
I have a problem during the first Initialisation. When the fundamental matrix is calculating there are two SV-Decomposations in the "ComputeF21"-Method. After the second one it called:

```
w.at<float>(2,2)=0;
```

The problem in my case is that the w-Matrix has always only one colum. So there is an access violation everytime. In the OpenCV-Method in lapack.cpp "cv::SVDecomp(Fpre,w,u,vt,cv::SVD::MODIFY_A | cv::SVD::FULL_UV)" the w-Matrix is always constructed like this: 

```
Mat temp_w(n, 1, type, buf + urows*astep);
```

So there can't be a second colum. Can anybody help me in this case ?

Best regards,
Sergej

**Comment by raulmur** [comment]
This was already fixed:
https://github.com/raulmur/ORB_SLAM/commit/ede1ed7ca764810bdd3d9c96eae70fa1b8e0e8be

Best,
Raúl
