### ISSUE TITLE
Hello, how to get the opencv camera calibration of rgb-d dataset from tum?

### ISSUE THREAD

**Issue by liqile** [raulmur/ORB_SLAM#6]
Hello
Thanks for your sharing of `ORB_SLAM`
Recently I am trying to run your code with `rgb-d dataset` from tum vision
But I don't know how to get the opencv camera calibration
could you please tell me how to access it
thanks in advance.

best
                                                                                     liqile

**Comment by raulmur** [comment]
http://vision.in.tum.de/data/datasets/rgbd-dataset/file_formats#intrinsic_camera_calibration_of_the_kinect
