### ISSUE TITLE
TemplatedVocabulary::loadFromTextFile wrongly extracts descriptor

### ISSUE THREAD

**Issue by ex-ratt** [raulmur/ORB_SLAM#66]
I was trying to use your vocabulary, but I had some problems with it. For once, it does not set the ID of the nodes (besides the root node), which is easy to fix. This will be a problem when saving the vocabulary again. The bigger problem is the extraction of the descriptor - the loop https://github.com/raulmur/ORB_SLAM/blob/7c7fb3daec2c1ade3b7f17ca36088a8be51c00dc/Thirdparty/DBoW2/DBoW2/TemplatedVocabulary.h#l1397 will result in the last value residing in the string `sd`, all the other values are discarded. FORB::fromString will silently fail (https://github.com/raulmur/ORB_SLAM/blob/aeaacbed761838e0a7177928932b77ac1d7f0d62/Thirdparty/DBoW2/DBoW2/FORB.cpp#l131), because there is only one value in the given string. So the last descriptor value will be the first one, while the rest of the descriptor stays as initialized, containing some more or less random values.

A fix for the ID issue is inserting this line just before `m_nodes[nid].parent = pid;`:

    m_nodes[nid].id = nid;

A possible fix for the descriptor issue would be:

    string sd;
    string sdv;
    for(int iD=0;iD<F::L;iD++) {
        ssnode >> sdv;
        sd += sdv;
        sd += ' ';
    }
    F::fromString(m_nodes[nid].descriptor, sd);

**Comment by raulmur** [comment]
Your are completely right @ex-ratt 
I have fixed it. Thanks a lot.
