### ISSUE TITLE
magic number in Optimizer.cc

### ISSUE THREAD

**Issue by mocibb** [raulmur/ORB_SLAM#67]
I cannot figure out what the meaning about  magic number 5.991 in Optimizer.cc?
Is this number fit well for all dataset?

const float chi2[4]={9.210,7.378,5.991,5.991};
const int its[4]={10,10,7,5};

would you explain some more about these number?

**Comment by sergiud** [comment]
Looks like `chi2` stores the critical values of the chi-squared distribution for two degrees of freedom. Not sure about `its` though.

**Comment by raulmur** [comment]
Those are inlier/outlier thresholds based on the chi2 test at 95%, 97.5% and 99%. See chapter 4.7 and Appendix 2 of Multiple View Geometry in Computer Vision (R. Hartley and A. Zisserman)
