### ISSUE TITLE
Hi, how to access the pose of the camera?

### ISSUE THREAD

**Issue by liqile** [raulmur/ORB_SLAM#7]
Hello, @raulmur 
I am sorry to trouble you but I am facing some problems while porting your code to an arm board.

The 1st problem is that I have no idea how to get the camera pose.
I have seen into your code, and found following lines
`        cv::Mat Rwc = mCurrentFrame.mTcw.rowRange(0,3).colRange(0,3).t();`
`        cv::Mat twc = -Rwc*mCurrentFrame.mTcw.rowRange(0,3).col(3);`
is `Rwc`the rotation matrix of the camera in world coordinate system?
and 
I am also wondering how to access the `(x,y,z)` coordinate of camera in world coordinate system?
is it `twc` or `mCurrentFrame.mTcw.rowRange(0,3).col(3)`?

The second problem is that how to remove the viewer and rviz of the program. Because I only need the pose of the camera. or how do I get to know all the topics with orbslam?

I am looking forward to hearing from you
best wishes to you

                                                                                                                 yours, sincerely
                                                                                                                 Li Qile

**Comment by raulmur** [comment]
subindex cw means that points in world coordinates are transformed into camera coordinates.
twc is the camera position (optical center) in world coordinates.
