### ISSUE TITLE
debug the code

### ISSUE THREAD

**Issue by Fahimkh** [raulmur/ORB_SLAM#77]
Hi,

I want to run this code in debug mode.. I am trying so hard but still I am not able to do that.. I want to start with main file and look the code deeply.. Please help me to find the way...

**Comment by raulmur** [comment]
I recommend you qtcreator. It can create a project just from the CMakeLists.txt

**Comment by weblucas** [comment]
Indeed, qtcreator is the best for this. http://wiki.ros.org/IDEs

**Comment by Fahimkh** [comment]
Thanks @raulmur  and @weblucas 
I followed the link but I am facing problem. I explain my problem

1-first I created a folder with name "ORB_WS" and in that folder I created another folder "sandbox".
2-then I downloaded the repository in "sandbox" folder.

my environment variables are like this
echo $ROS_PACKAGE_PATH
/home/faheem/ORB_WS/sandbox:/opt/ros/indigo/share:/opt/ros/indigo/stacks

echo $ROS_ROOT
/opt/ros/indigo/share/ros

3- I opened Qtcreator from terminal 
cd /home/faheem/Qt/Tools/QtCreator/bin
./qtcreator

4-After starting qtcreator I did following steps
    File --> Open File or Project...

5-I selected CMakeList.txt from ORB_SLAM folder

6-Then created a "build" folder in ORB_SLAM folder. I did this as I am following this link
http://wiki.ros.org/IDEs

7- I have attached all the snapshoots. After finishing I can see my source files.

Problem is that I can't see Thirdparty. When I put break point at the start of the main and run debug I  got error for Thirdparty. I dont know how to include this.

![screenshot from 2015-11-09 20 41 00](https://cloud.githubusercontent.com/assets/14022744/11053065/5f7497d0-8723-11e5-94a6-772696bd84b6.png)

![screenshot from 2015-11-09 20 41 39](https://cloud.githubusercontent.com/assets/14022744/11053078/7c662980-8723-11e5-97ac-0614c4b068ff.png)

![screenshot from 2015-11-09 20 42 40](https://cloud.githubusercontent.com/assets/14022744/11053079/7d6fdf42-8723-11e5-8016-f483b100d9b7.png)

![screenshot from 2015-11-09 20 48 23](https://cloud.githubusercontent.com/assets/14022744/11053080/7ede69ac-8723-11e5-86c1-d31d44f836dc.png)

**Comment by amiltonwong** [comment]
I had also followed steps from @Fahimkh , I also came across compile error (but a bit different) 
https://goo.gl/MFG4hM
It'll be greatly appreciated if one gives some suggestions~

**Comment by Fahimkh** [comment]
Now I changed my method. But still facing one problem. I explain my working here

1-(same before)first I created a folder with name "ORB_WS" and in that folder I created another folder "sandbox".
2-(same before)then I downloaded the repository in "sandbox" folder.

my environment variables are like this
echo $ROS_PACKAGE_PATH
/home/faheem/ORB_WS/sandbox:/opt/ros/indigo/share:/opt/ros/indigo/stacks

echo $ROS_ROOT
/opt/ros/indigo/share/ros

3- (same before)I opened Qtcreator from terminal
cd /home/faheem/Qt/Tools/QtCreator/bin
./qtcreator

4-(same before)starting qtcreator

5a- File --> Open File or Project...
5b- First I opened g2o in Third party and added its CMakelist.txt
![screenshot from 2015-11-09 23 10 09](https://cloud.githubusercontent.com/assets/14022744/11055053/961b7672-8738-11e5-820b-3d73a50c8a1b.png)


5c- Then I made a build folder in it and then I pressed "Run CMake" but with argument and I put this argument there ".. -DCMAKE_BUILD_TYPE=Debug"
![screenshot from 2015-11-09 23 11 21](https://cloud.githubusercontent.com/assets/14022744/11055054/98526414-8738-11e5-984f-0171dfd5283f.png)

6- I did this for DBoW2 and ORB_SLAM main folder. But I changed argument for ORB_SLAM main folder. In that case I put this argument ".. -DROS_BUILD_TYPE=Debug"

![screenshot from 2015-11-09 23 22 40](https://cloud.githubusercontent.com/assets/14022744/11055124/54213454-8739-11e5-93ff-92320074a261.png)

7- After that I double click on main.cc to open it in window. I put a break point and run the debug mode. I got this error

"make[3]: *** No rule to make target `../Thirdparty/DBoW2/lib/libDBoW2.so', needed by `../bin/ORB_SLAM'.  Stop.
make[2]: *** [CMakeFiles/ORB_SLAM.dir/all] Error 2
make[1]: *** [CMakeFiles/ORB_SLAM.dir/rule] Error 2
make: *** [ORB_SLAM] Error 2
23:27:46: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project ORB_SLAM (kit: Desktop Qt 5.3 GCC 64bit)
When executing step "Make""
![screenshot from 2015-11-09 23 28 30](https://cloud.githubusercontent.com/assets/14022744/11055160/ac6fc63e-8739-11e5-9c98-885bdf299603.png)

@raulmur  @weblucas  please look on...

@amiltonwong  you can try this.. and if you find some solution please let me know...

**Comment by raulmur** [comment]
Build first DBoW2 and g2o then build ORB-SLAM

**Comment by Fahimkh** [comment]
@raulmur  I did it but still getting same error.. I think there is some problem in arguments that I am providing. Can you please check those arguments in above comment.

**Comment by raulmur** [comment]
If I am not wrong the error in your last post is that DBoW2 is not found when building ORB-SLAM. You mentioned you ran CMake for DBoW2 and g2o but you did not build them separately before building ORB-SLAM.

**Comment by Fahimkh** [comment]
Now it is working... :-) ... Basically I was putting this argment for "Run CMake" ..".. -DROS_BUILD_TYPE=Debug" and for g2o and DBoW2... When I changed this argument to ".. -DROS_BUILD_TYPE=Release" it started working...

How can I provide path to vocabulary and settings file in debug mode.
I am really thankful to you @raulmur

**Comment by Fahimkh** [comment]
Sorry @raulmur  I am disturbing you.. I did this as well..
on the left side there is project tab.. pressed it and enter command line arguments...
