### ISSUE TITLE
Rosrun ORB_SLAM-master ... unable to run

### ISSUE THREAD

**Issue by chaiein** [raulmur/ORB_SLAM#80]
When I use rosrun ORB_SLAM-master <path_of_vocabulary file which is in txt form>  <setting.yaml path> I get th below error. I am using jade version. 
**[rospack] Error: package 'ORB_SLAM' not found **
**[librospack]: error while executing command**

**Comment by Parnia** [comment]
did you add the path of ORB_SLAM to ROS_PACKAGE_PATH?

for example:
export ROS_PACKAGE_PATH=/opt/ros/jade/share:/opt/ros/jade/stacks:/home/parnia/ORB_SLAM

"/home/parnia/ORB_SLAM" this is the path I added

**Comment by chaiein** [comment]
It works after adding the path.
