### ISSUE TITLE
File ORBvoc.txt

### ISSUE THREAD

**Issue by StasiaS** [raulmur/ORB_SLAM#84]
Good Day!

Tell me please, how the contents of the file ORBvoc.txt should be interpreted?
Should it be modified in any way for my specific camera, and if so how/where?

**Comment by Beewe** [comment]
Don't change the contents of the file unless you want to create an own bag of (visual) words. But in general, there is no need to, as stated in the paper. The only thing you need to change when using your camera is the calibration data within the settings file.

**Comment by StasiaS** [comment]
Thank you for your answer!
