### ISSUE TITLE
rviz topics to view

### ISSUE THREAD

**Issue by chaiein** [raulmur/ORB_SLAM#85]
how to view the topics in rviz related to ORB_SLAM. I am not able visualise any map on the display.

**Comment by paulinus** [comment]
I was having the same problem. What worked for me was to run ORB_SLAM using the provided launcher
```
roslaunch ExampleGroovyOrNewer.launch
```
And then starting rviz
```
rosrun rviz rviz -d Data/rviz.rviz
```
For some reason, i start ORB_SLAM manually, rviz complains about not finding [map] in Fixed Frame
