### ISSUE TITLE
rosrun ORB_ SLAM & rviz & ORB_SLAM/Frame is still black  

### ISSUE THREAD

**Issue by mhzaki** [raulmur/ORB_SLAM#92]
HELLO every body !
I download the package of     I catkinized it but when i run the example.bag thent launch the ExampleGroovyHydro.launch i don't see any thin in the window untitled ORB_SLAM/Frame 
eventhogh i am sur that there is data in the topic camera/image_view;
I don't know what's wrong

**Comment by Loeing** [comment]
Did you solve this? I had to reinstall everything and I'm running into the same problem

**Comment by Loeing** [comment]
never mind
